on:
  schedule:
    - cron: '0 8 * * *'
      timezone: Asia/Tokyo
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 26

      - run: |
          if ! bin/today-is-before.ts 31; then
            exit 0
          fi
          curl -sSf "$URL"
        env:
          URL: ${{ secrets.D31 }}
