on:
  schedule:
    - cron: '0 9 * * *'
      timezone: Asia/Tokyo
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 26

      - run: |
          if ! bin/today-is-after.ts 20; then
            exit 0
          fi
          echo $URLS | xargs -n1 curl -sSf
        env:
          URLS: ${{ secrets.D31 }}
