on:
  schedule:
    - cron: '0 9 * * *'
      timezone: Asia/Tokyo

jobs:
  trigger:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@6

      - uses: actions/setup-node@v6
        with:
          node-version: 26

      - run: |
          if ! bin/today-is-after.ts 20; then
            echo NOT OK # TEST
          fi
          echo OK # TEST
